version: 2

models:
  - name: stg_orders
    description: "Staging view for raw orders data loaded via ingestion service."
    columns:
      - name: order_id
        description: "Primary key for an order."
        tests:
          - not_null
          - unique
      - name: customer_name
        description: "Name of the customer placing the order."
      - name: total_amount
        description: "Monetary value of the order."

