name: pluto_duck_core
version: 1.0.0
profile: pluto_duck
model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
target-path: target
clean-targets: ["target"]

models:
  pluto_duck_core:
    staging:
      +materialized: view
    marts:
      +materialized: table

